/* This file was automatically generated by CasADi 3.6.5.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) MPC_V0_env_0_i_8_sempc_dyn_disc_phi_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[22] = {18, 1, 0, 18, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17};
static const casadi_int casadi_s3[30] = {8, 5, 0, 6, 12, 17, 20, 22, 0, 1, 2, 3, 5, 6, 0, 1, 2, 4, 5, 6, 0, 1, 2, 5, 6, 0, 2, 6, 2, 7};

/* MPC_V0_env_0_i_8_sempc_dyn_disc_phi_fun_jac:(i0[5],i1[3],i2[18])->(o0[5],o1[8x5,22nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a6, a7, a8, a9;
  a0=arg[0]? arg[0][0] : 0;
  a1=arg[1]? arg[1][2] : 0;
  a2=6.;
  a2=(a1/a2);
  a3=arg[0]? arg[0][3] : 0;
  a4=arg[0]? arg[0][2] : 0;
  a5=1.7380000000000000e-02;
  a6=arg[1]? arg[1][1] : 0;
  a7=tan(a6);
  a7=(a5*a7);
  a8=2.8430000000000000e-02;
  a7=(a7/a8);
  a8=atan(a7);
  a9=(a4+a8);
  a10=cos(a9);
  a11=(a3*a10);
  a12=2.;
  a13=(a1/a12);
  a14=arg[1]? arg[1][0] : 0;
  a15=(a13*a14);
  a15=(a3+a15);
  a16=sin(a8);
  a17=(a3*a16);
  a17=(a17/a5);
  a18=(a13*a17);
  a18=(a4+a18);
  a19=(a18+a8);
  a20=cos(a19);
  a21=(a15*a20);
  a21=(a12*a21);
  a11=(a11+a21);
  a21=(a1/a12);
  a22=(a21*a14);
  a22=(a3+a22);
  a23=(a15*a16);
  a23=(a23/a5);
  a24=(a21*a23);
  a24=(a4+a24);
  a25=(a24+a8);
  a26=cos(a25);
  a27=(a22*a26);
  a27=(a12*a27);
  a11=(a11+a27);
  a27=(a1*a14);
  a27=(a3+a27);
  a28=(a22*a16);
  a28=(a28/a5);
  a29=(a1*a28);
  a29=(a4+a29);
  a30=(a29+a8);
  a31=cos(a30);
  a32=(a27*a31);
  a11=(a11+a32);
  a32=(a2*a11);
  a0=(a0+a32);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][1] : 0;
  a32=(a4+a8);
  a33=sin(a32);
  a34=(a3*a33);
  a18=(a18+a8);
  a35=sin(a18);
  a36=(a15*a35);
  a36=(a12*a36);
  a34=(a34+a36);
  a24=(a24+a8);
  a36=sin(a24);
  a37=(a22*a36);
  a37=(a12*a37);
  a34=(a34+a37);
  a29=(a29+a8);
  a37=sin(a29);
  a38=(a27*a37);
  a34=(a34+a38);
  a38=(a2*a34);
  a0=(a0+a38);
  if (res[0]!=0) res[0][1]=a0;
  a0=(a12*a23);
  a0=(a17+a0);
  a38=(a12*a28);
  a0=(a0+a38);
  a38=(a27*a16);
  a38=(a38/a5);
  a0=(a0+a38);
  a38=(a2*a0);
  a4=(a4+a38);
  if (res[0]!=0) res[0][2]=a4;
  a4=(a12*a14);
  a4=(a14+a4);
  a38=(a12*a14);
  a4=(a4+a38);
  a4=(a4+a14);
  a38=(a2*a4);
  a38=(a3+a38);
  if (res[0]!=0) res[0][3]=a38;
  a38=arg[0]? arg[0][4] : 0;
  a38=(a38+a1);
  if (res[0]!=0) res[0][4]=a38;
  a38=(a20*a13);
  a38=(a12*a38);
  a39=(a26*a21);
  a25=sin(a25);
  a40=5.7537399309551212e+01;
  a41=(a16*a13);
  a41=(a40*a41);
  a42=(a21*a41);
  a43=(a25*a42);
  a43=(a22*a43);
  a39=(a39-a43);
  a39=(a12*a39);
  a38=(a38+a39);
  a39=(a31*a1);
  a30=sin(a30);
  a43=(a16*a21);
  a43=(a40*a43);
  a44=(a1*a43);
  a45=(a30*a44);
  a45=(a27*a45);
  a39=(a39-a45);
  a38=(a38+a39);
  a38=(a2*a38);
  if (res[1]!=0) res[1][0]=a38;
  a9=sin(a9);
  a38=3.5174111853675697e+01;
  a6=cos(a6);
  a6=casadi_sq(a6);
  a5=(a5/a6);
  a38=(a38*a5);
  a5=1.;
  a7=casadi_sq(a7);
  a7=(a5+a7);
  a38=(a38/a7);
  a7=(a9*a38);
  a7=(a3*a7);
  a19=sin(a19);
  a8=cos(a8);
  a8=(a8*a38);
  a6=(a3*a8);
  a6=(a40*a6);
  a39=(a13*a6);
  a45=(a39+a38);
  a45=(a19*a45);
  a45=(a15*a45);
  a45=(a12*a45);
  a7=(a7+a45);
  a45=(a15*a8);
  a45=(a40*a45);
  a46=(a21*a45);
  a47=(a46+a38);
  a47=(a25*a47);
  a47=(a22*a47);
  a47=(a12*a47);
  a7=(a7+a47);
  a47=(a22*a8);
  a47=(a40*a47);
  a48=(a1*a47);
  a49=(a48+a38);
  a49=(a30*a49);
  a49=(a27*a49);
  a7=(a7+a49);
  a7=(a2*a7);
  a7=(-a7);
  if (res[1]!=0) res[1][1]=a7;
  a7=1.6666666666666666e-01;
  a11=(a7*a11);
  a49=5.0000000000000000e-01;
  a50=(a49*a14);
  a51=(a20*a50);
  a17=(a49*a17);
  a52=(a19*a17);
  a52=(a15*a52);
  a51=(a51-a52);
  a51=(a12*a51);
  a52=(a49*a14);
  a53=(a26*a52);
  a49=(a49*a23);
  a23=(a16*a50);
  a23=(a40*a23);
  a54=(a21*a23);
  a49=(a49+a54);
  a54=(a25*a49);
  a54=(a22*a54);
  a53=(a53-a54);
  a53=(a12*a53);
  a51=(a51+a53);
  a53=(a31*a14);
  a54=(a16*a52);
  a54=(a40*a54);
  a55=(a1*a54);
  a28=(a28+a55);
  a55=(a30*a28);
  a55=(a27*a55);
  a53=(a53-a55);
  a51=(a51+a53);
  a51=(a2*a51);
  a11=(a11+a51);
  if (res[1]!=0) res[1][2]=a11;
  if (res[1]!=0) res[1][3]=a5;
  a9=(a3*a9);
  a11=(a15*a19);
  a11=(a12*a11);
  a9=(a9+a11);
  a11=(a22*a25);
  a11=(a12*a11);
  a9=(a9+a11);
  a11=(a27*a30);
  a9=(a9+a11);
  a9=(a2*a9);
  a9=(-a9);
  if (res[1]!=0) res[1][4]=a9;
  a9=(a40*a16);
  a11=(a13*a9);
  a19=(a19*a11);
  a19=(a15*a19);
  a20=(a20-a19);
  a20=(a12*a20);
  a10=(a10+a20);
  a20=(a40*a16);
  a19=(a21*a20);
  a25=(a25*a19);
  a25=(a22*a25);
  a26=(a26-a25);
  a26=(a12*a26);
  a10=(a10+a26);
  a26=(a40*a16);
  a25=(a1*a26);
  a30=(a30*a25);
  a30=(a27*a30);
  a31=(a31-a30);
  a10=(a10+a31);
  a10=(a2*a10);
  if (res[1]!=0) res[1][5]=a10;
  a13=(a35*a13);
  a13=(a12*a13);
  a21=(a36*a21);
  a24=cos(a24);
  a42=(a24*a42);
  a42=(a22*a42);
  a21=(a21+a42);
  a21=(a12*a21);
  a13=(a13+a21);
  a21=(a37*a1);
  a29=cos(a29);
  a44=(a29*a44);
  a44=(a27*a44);
  a21=(a21+a44);
  a13=(a13+a21);
  a13=(a2*a13);
  if (res[1]!=0) res[1][6]=a13;
  a32=cos(a32);
  a13=(a32*a38);
  a13=(a3*a13);
  a18=cos(a18);
  a39=(a39+a38);
  a39=(a18*a39);
  a39=(a15*a39);
  a39=(a12*a39);
  a13=(a13+a39);
  a46=(a46+a38);
  a46=(a24*a46);
  a46=(a22*a46);
  a46=(a12*a46);
  a13=(a13+a46);
  a48=(a48+a38);
  a48=(a29*a48);
  a48=(a27*a48);
  a13=(a13+a48);
  a13=(a2*a13);
  if (res[1]!=0) res[1][7]=a13;
  a34=(a7*a34);
  a50=(a35*a50);
  a17=(a18*a17);
  a17=(a15*a17);
  a50=(a50+a17);
  a50=(a12*a50);
  a52=(a36*a52);
  a49=(a24*a49);
  a49=(a22*a49);
  a52=(a52+a49);
  a52=(a12*a52);
  a50=(a50+a52);
  a52=(a37*a14);
  a28=(a29*a28);
  a28=(a27*a28);
  a52=(a52+a28);
  a50=(a50+a52);
  a50=(a2*a50);
  a34=(a34+a50);
  if (res[1]!=0) res[1][8]=a34;
  if (res[1]!=0) res[1][9]=a5;
  a3=(a3*a32);
  a32=(a15*a18);
  a32=(a12*a32);
  a3=(a3+a32);
  a32=(a22*a24);
  a32=(a12*a32);
  a3=(a3+a32);
  a32=(a27*a29);
  a3=(a3+a32);
  a3=(a2*a3);
  if (res[1]!=0) res[1][10]=a3;
  a18=(a18*a11);
  a15=(a15*a18);
  a35=(a35+a15);
  a35=(a12*a35);
  a33=(a33+a35);
  a24=(a24*a19);
  a22=(a22*a24);
  a36=(a36+a22);
  a36=(a12*a36);
  a33=(a33+a36);
  a29=(a29*a25);
  a29=(a27*a29);
  a37=(a37+a29);
  a33=(a33+a37);
  a33=(a2*a33);
  if (res[1]!=0) res[1][11]=a33;
  a41=(a12*a41);
  a43=(a12*a43);
  a41=(a41+a43);
  a43=(a16*a1);
  a43=(a40*a43);
  a41=(a41+a43);
  a41=(a2*a41);
  if (res[1]!=0) res[1][12]=a41;
  a45=(a12*a45);
  a6=(a6+a45);
  a47=(a12*a47);
  a6=(a6+a47);
  a27=(a27*a8);
  a27=(a40*a27);
  a6=(a6+a27);
  a6=(a2*a6);
  if (res[1]!=0) res[1][13]=a6;
  a0=(a7*a0);
  a23=(a12*a23);
  a54=(a12*a54);
  a23=(a23+a54);
  a14=(a16*a14);
  a14=(a40*a14);
  a23=(a23+a14);
  a23=(a2*a23);
  a0=(a0+a23);
  if (res[1]!=0) res[1][14]=a0;
  if (res[1]!=0) res[1][15]=a5;
  a20=(a12*a20);
  a9=(a9+a20);
  a12=(a12*a26);
  a9=(a9+a12);
  a40=(a40*a16);
  a9=(a9+a40);
  a2=(a2*a9);
  if (res[1]!=0) res[1][16]=a2;
  if (res[1]!=0) res[1][17]=a1;
  a7=(a7*a4);
  if (res[1]!=0) res[1][18]=a7;
  if (res[1]!=0) res[1][19]=a5;
  if (res[1]!=0) res[1][20]=a5;
  if (res[1]!=0) res[1][21]=a5;
  return 0;
}

CASADI_SYMBOL_EXPORT int MPC_V0_env_0_i_8_sempc_dyn_disc_phi_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int MPC_V0_env_0_i_8_sempc_dyn_disc_phi_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int MPC_V0_env_0_i_8_sempc_dyn_disc_phi_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void MPC_V0_env_0_i_8_sempc_dyn_disc_phi_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int MPC_V0_env_0_i_8_sempc_dyn_disc_phi_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void MPC_V0_env_0_i_8_sempc_dyn_disc_phi_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void MPC_V0_env_0_i_8_sempc_dyn_disc_phi_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void MPC_V0_env_0_i_8_sempc_dyn_disc_phi_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int MPC_V0_env_0_i_8_sempc_dyn_disc_phi_fun_jac_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int MPC_V0_env_0_i_8_sempc_dyn_disc_phi_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real MPC_V0_env_0_i_8_sempc_dyn_disc_phi_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* MPC_V0_env_0_i_8_sempc_dyn_disc_phi_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* MPC_V0_env_0_i_8_sempc_dyn_disc_phi_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* MPC_V0_env_0_i_8_sempc_dyn_disc_phi_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* MPC_V0_env_0_i_8_sempc_dyn_disc_phi_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int MPC_V0_env_0_i_8_sempc_dyn_disc_phi_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int MPC_V0_env_0_i_8_sempc_dyn_disc_phi_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
